# (C) 2001-2015 Altera Corporation. All rights reserved.
# Your use of Altera Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License Subscription 
# Agreement, Altera MegaCore Function License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Altera and sold by 
# Altera or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


# +----------------------------------------------------------------------------+
# |                                                                            |
# | Any megafunction design, and related net list (encrypted or decrypted),    |
# |  support information, device programming or simulation file, and any other |
# |  associated documentation or information provided by Altera or a partner   |
# |  under Altera's Megafunction Partnership Program may be used only to       |
# |  program PLD devices (but not masked PLD devices) from Altera.  Any other  |
# |  use of such megafunction design, net list, support information, device    |
# |  programming or simulation file, or any other related documentation or     |
# |  information is prohibited for any other purpose, including, but not       |
# |  limited to modification, reverse engineering, de-compiling, or use with   |
# |  any other silicon devices, unless such use is explicitly licensed under   |
# |  a separate agreement with Altera or a megafunction partner.  Title to     |
# |  the intellectual property, including patents, copyrights, trademarks,     |
# |  trade secrets, or maskworks, embodied in any such megafunction design,    |
# |  net list, support information, device programming or simulation file, or  |
# |  any other related documentation or information provided by Altera or a    |
# |  megafunction partner, remains with Altera, the megafunction partner, or   |
# |  their respective licensors.  No other licenses, including any licenses    |
# |  needed under any third party's intellectual property, are provided herein.|
# |  Copying or modifying any file, or portion thereof, to which this notice   |
# |  is attached violates this copyright.                                      |
# |                                                                            |
# | THIS FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR    |
# | IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,   |
# | FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL    |
# | THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER |
# | LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING    |
# | FROM, OUT OF OR IN CONNECTION WITH THIS FILE OR THE USE OR OTHER DEALINGS  |
# | IN THIS FILE.                                                              |
# |                                                                            |
# | This agreement shall be governed in all respects by the laws of the State  |
# |  of California and by the laws of the United States of America.            |
# |                                                                            |
# +----------------------------------------------------------------------------+

# TCL File Generated by Altera University Program
# DO NOT MODIFY

source "../../lib/aup_version.tcl"
source "../../lib/aup_ip_generator.tcl"

# +-----------------------------------
# | module altera_up_avalon_rs232
# | 
set_module_property DESCRIPTION "RS232 UART Controller"
set_module_property NAME altera_up_avalon_rs232
set_module_property VERSION $aup_version
set_module_property GROUP "University Program/Communications"
set_module_property AUTHOR "Altera University Program"
set_module_property DISPLAY_NAME "RS232 UART"
set_module_property DATASHEET_URL "[pwd]/doc/RS232.pdf"
#set_module_property TOP_LEVEL_HDL_FILE altera_up_avalon_rs232.v
#set_module_property TOP_LEVEL_HDL_MODULE altera_up_avalon_rs232
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL false
set_module_property ELABORATION_CALLBACK elaborate
set_module_property GENERATION_CALLBACK generate
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
#add_file altera_up_avalon_rs232.v {SYNTHESIS SIMULATION}
add_file "hdl/altera_up_rs232_counters.v" {SYNTHESIS SIMULATION}
add_file "hdl/altera_up_rs232_in_deserializer.v" {SYNTHESIS SIMULATION}
add_file "hdl/altera_up_rs232_out_serializer.v" {SYNTHESIS SIMULATION}
add_file "hdl/altera_up_sync_fifo.v" {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter avalon_bus_type string "Memory Mapped"
set_parameter_property avalon_bus_type DISPLAY_NAME "Avalon Type"
set_parameter_property avalon_bus_type GROUP "Interface Settings"
set_parameter_property avalon_bus_type UNITS None
set_parameter_property avalon_bus_type AFFECTS_ELABORATION true
set_parameter_property avalon_bus_type AFFECTS_GENERATION true
set_parameter_property avalon_bus_type ALLOWED_RANGES {"Memory Mapped" "Streaming"}
set_parameter_property avalon_bus_type VISIBLE true
set_parameter_property avalon_bus_type ENABLED true

add_parameter clk_rate integer 50000000
set_parameter_property clk_rate DISPLAY_NAME "Incoming clock rate"
set_parameter_property clk_rate GROUP "Interface Settings"
set_parameter_property clk_rate UNITS hertz
set_parameter_property clk_rate AFFECTS_ELABORATION true
set_parameter_property clk_rate AFFECTS_GENERATION true
set_parameter_property clk_rate VISIBLE false
set_parameter_property clk_rate ENABLED true

add_parameter baud integer 115200
set_parameter_property baud DISPLAY_NAME "Baud Rate (bps)"
set_parameter_property baud GROUP "Baud Rate"
set_parameter_property baud UNITS None
set_parameter_property baud AFFECTS_ELABORATION true
set_parameter_property baud AFFECTS_GENERATION true
set_parameter_property baud ALLOWED_RANGES {115200 57600 38400 31250 28800 19910 14400 9600 4800 2400 1200 300}
set_parameter_property baud VISIBLE true
set_parameter_property baud ENABLED true

add_parameter parity string None
set_parameter_property parity DISPLAY_NAME "Parity"
set_parameter_property parity GROUP "Data Format"
set_parameter_property parity UNITS None
set_parameter_property parity AFFECTS_ELABORATION true
set_parameter_property parity AFFECTS_GENERATION true
set_parameter_property parity ALLOWED_RANGES {None Odd Even}
set_parameter_property parity VISIBLE true
set_parameter_property parity ENABLED true

add_parameter data_bits integer 8
set_parameter_property data_bits DISPLAY_NAME "Data Bits"
set_parameter_property data_bits GROUP "Data Format"
set_parameter_property data_bits UNITS None
set_parameter_property data_bits AFFECTS_ELABORATION true
set_parameter_property data_bits AFFECTS_GENERATION true
set_parameter_property data_bits ALLOWED_RANGES {7 8 9}
set_parameter_property data_bits VISIBLE true
set_parameter_property data_bits ENABLED true

add_parameter stop_bits integer 1
set_parameter_property stop_bits DISPLAY_NAME "Stop Bits"
set_parameter_property stop_bits GROUP "Data Format"
set_parameter_property stop_bits UNITS None
set_parameter_property stop_bits AFFECTS_ELABORATION true
set_parameter_property stop_bits AFFECTS_GENERATION true
set_parameter_property stop_bits ALLOWED_RANGES {1 2}
set_parameter_property stop_bits VISIBLE true
set_parameter_property stop_bits ENABLED true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk clock end
set_interface_property clk enabled true

add_interface_port clk clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset enabled true
set_interface_property reset synchronousEdges DEASSERT

add_interface_port reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | Elaboration function
# | 
proc elaborate {} {
	set avalon_bus_type	[ get_parameter_value "avalon_bus_type" ]
	set baud [ get_parameter_value "baud" ]
	set parity [ get_parameter_value "parity" ]
	set data_bits [ get_parameter_value "data_bits" ]
	set stop_bits [ get_parameter_value "stop_bits" ]

	set clk_rate [ get_interface_property clk clockRate ]
	if { $clk_rate <= 0 } {
		set_parameter_property clk_rate VISIBLE true
	} else {
		set_parameter_property clk_rate VISIBLE false
		set_parameter_value "clk_rate" $clk_rate
	}

	if { $avalon_bus_type == "Memory Mapped" } {
		# +-----------------------------------
		# | connection point avalon_rs232_slave
		# | 
		add_interface avalon_rs232_slave avalon end
		set_interface_property avalon_rs232_slave addressAlignment DYNAMIC
		set_interface_property avalon_rs232_slave associatedClock clk
		set_interface_property avalon_rs232_slave associatedReset reset
		set_interface_property avalon_rs232_slave bridgesToMaster ""
		set_interface_property avalon_rs232_slave burstOnBurstBoundariesOnly false
		#set_interface_property avalon_rs232_slave explicitAddressSpan 8
		set_interface_property avalon_rs232_slave holdTime 0
		set_interface_property avalon_rs232_slave isBigEndian  false
		set_interface_property avalon_rs232_slave isFlash false
		set_interface_property avalon_rs232_slave isMemoryDevice false
		set_interface_property avalon_rs232_slave isNonVolatileStorage false
		set_interface_property avalon_rs232_slave linewrapBursts false
		set_interface_property avalon_rs232_slave maximumPendingReadTransactions 0
		set_interface_property avalon_rs232_slave minimumUninterruptedRunLength 1
		set_interface_property avalon_rs232_slave printableDevice false
		set_interface_property avalon_rs232_slave readLatency 1
		set_interface_property avalon_rs232_slave readWaitTime 0
		set_interface_property avalon_rs232_slave setupTime 0
		set_interface_property avalon_rs232_slave timingUnits cycles
		set_interface_property avalon_rs232_slave writeWaitTime 0

		add_interface_port avalon_rs232_slave address address Input 1
		add_interface_port avalon_rs232_slave chipselect chipselect Input 1
		add_interface_port avalon_rs232_slave byteenable byteenable Input 4
		add_interface_port avalon_rs232_slave read read Input 1
		add_interface_port avalon_rs232_slave write write Input 1
		add_interface_port avalon_rs232_slave writedata writedata Input 32
		add_interface_port avalon_rs232_slave readdata readdata Output 32
		# | 
		# +-----------------------------------

		# +-----------------------------------
		# | connection point interrupt
		# | 
		add_interface interrupt interrupt end
		set_interface_property interrupt associatedAddressablePoint avalon_rs232_slave
		set_interface_property interrupt associatedClock clk
		set_interface_property interrupt associatedReset reset

		add_interface_port interrupt irq irq Output 1
		# | 
		# +-----------------------------------
	} else {
		# +-----------------------------------
		# | connection point avalon_data_receive_source
		# | 
		add_interface avalon_data_receive_source avalon_streaming start
		set_interface_property avalon_data_receive_source associatedClock clk
		set_interface_property avalon_data_receive_source associatedReset reset
		set_interface_property avalon_data_receive_source errorDescriptor ""
		set_interface_property avalon_data_receive_source maxChannel 0
		set_interface_property avalon_data_receive_source readyLatency 0

		add_interface_port avalon_data_receive_source from_uart_ready ready Input 1
		add_interface_port avalon_data_receive_source from_uart_data data Output $data_bits
		add_interface_port avalon_data_receive_source from_uart_error error Output 1
		add_interface_port avalon_data_receive_source from_uart_valid valid Output 1
		# | 
		# +-----------------------------------

		# +-----------------------------------
		# | connection point avalon_data_transmit_sink
		# | 
		add_interface avalon_data_transmit_sink avalon_streaming end
		set_interface_property avalon_data_transmit_sink associatedClock clk
		set_interface_property avalon_data_transmit_sink associatedReset reset
		set_interface_property avalon_data_transmit_sink errorDescriptor ""
		set_interface_property avalon_data_transmit_sink maxChannel 0
		set_interface_property avalon_data_transmit_sink readyLatency 0

		add_interface_port avalon_data_transmit_sink to_uart_data data Input $data_bits
		add_interface_port avalon_data_transmit_sink to_uart_error error Input 1
		add_interface_port avalon_data_transmit_sink to_uart_valid valid Input 1
		add_interface_port avalon_data_transmit_sink to_uart_ready ready Output 1
		# | 
		# +-----------------------------------
	}
	
	# +-----------------------------------
	# | connection point external_interface
	# | 
	add_interface external_interface conduit end 

	add_interface_port external_interface UART_RXD export Input 1
	add_interface_port external_interface UART_TXD export Output 1
	# | 
	# +-----------------------------------
}
# | 
# +-----------------------------------

# +-----------------------------------
# | Generation function
# | 
proc generate {} {
	send_message info "Starting Generation of RS232 UART"

	# get parameter values
	set avalon_bus_type	[ get_parameter_value "avalon_bus_type" ]
	set baud [ get_parameter_value "baud" ]
	set parity [ get_parameter_value "parity" ]
	set data_bits [ get_parameter_value "data_bits" ]
	set stop_bits [ get_parameter_value "stop_bits" ]
	set clk_rate [ get_parameter_value "clk_rate" ]

	set counter_width  [ format "%.0f" [ expr ceil (log($clk_rate / $baud) / (log (2))) ] ]

	set baud_counter_width			"CW:$counter_width"
	set baud_tick_count				[ format "BAUD_TICK_COUNT:%.0f" [ expr $clk_rate / $baud ] ]
	set half_baud_tick_increment	[ format "HALF_BAUD_TICK_COUNT:%.0f" [ expr $clk_rate / ($baud * 2) ] ]

	if { $parity == "None" } {
		set total_data_width		[ format "TDW:%d" [ expr 1 + ($data_bits + $stop_bits) ] ]
	} else {
		set total_data_width		[ format "TDW:%d" [ expr 2 + ($data_bits + $stop_bits) ] ]
	}
	set data_width					"DW:$data_bits"
	if { $parity == "Odd" } {
		set odd_parity				"ODD_PARITY:1'b1"
	} else {
		set odd_parity				"ODD_PARITY:1'b0"
	}

	# set section values
	if { $parity == "None" } {
		set use_parity	"USE_PARITY:0"
	} else {
		set use_parity	"USE_PARITY:1"
	}
	if { $data_bits == 7 } {
		set use_dw_7	"USE_DATA_WIDTH_7:1"
		set use_dw_8	"USE_DATA_WIDTH_8:0"
	} elseif { $data_bits == 8 } {
		set use_dw_7	"USE_DATA_WIDTH_7:0"
		set use_dw_8	"USE_DATA_WIDTH_8:1"
	} else {
		set use_dw_7	"USE_DATA_WIDTH_7:0"
		set use_dw_8	"USE_DATA_WIDTH_8:0"
	}

	# set arguments
	set params "$baud_counter_width;$baud_tick_count;$half_baud_tick_increment;$total_data_width;$data_width;$odd_parity"
	set sections "$use_parity;$use_dw_7;$use_dw_8"

	# get generation settings
#	set dest_language	[ get_generation_property HDL_LANGUAGE ]
	set dest_dir 		[ get_generation_property OUTPUT_DIRECTORY ]
	set dest_name		[ get_generation_property OUTPUT_NAME ]
	
	add_file "$dest_dir$dest_name.v" {SYNTHESIS SIMULATION}
	# add_file "$dest_dir/altera_up_rs232_counters.v" SYNTHESIS
	# add_file "$dest_dir/altera_up_rs232_in_deserializer.v" SYNTHESIS
	# add_file "$dest_dir/altera_up_rs232_out_serializer.v" SYNTHESIS
	# add_file "$dest_dir/altera_up_sync_fifo.v" SYNTHESIS

	# Generate HDL
	if { $avalon_bus_type == "Memory Mapped" } {
		alt_up_generate "$dest_dir$dest_name.v" "hdl/altera_up_avalon_mm_rs232.v" "altera_up_avalon_mm_rs232" $dest_name $params $sections
	} else {
		alt_up_generate "$dest_dir$dest_name.v" "hdl/altera_up_avalon_st_rs232.v" "altera_up_avalon_st_rs232" $dest_name $params $sections
	}

	# file copy -force "hdl/altera_up_rs232_counters.v" $dest_dir
	# file copy -force "hdl/altera_up_rs232_in_deserializer.v" $dest_dir
	# file copy -force "hdl/altera_up_rs232_out_serializer.v" $dest_dir
	# file copy -force "hdl/altera_up_sync_fifo.v" $dest_dir

	# generate top level template
	#alt_up_create_instantiation_template "$dest_dir$dest_name.inst.v" $dest_name "external_interface"
}
# | 
# +-----------------------------------

